const imageParams = "?auto=format&fit=crop&w=800&q=80";

export const menuItems = [
  {
    id: 1,
    name: "Chicken Dum Biryani",
    category: "Biryani",
    price: 249,
    emoji: "🍗",
    description: "Aromatic rice, juicy chicken and slow-cooked masala.",
    imageUrl: `https://images.unsplash.com/photo-1633945274309-2c16c9682a8c${imageParams}`,
  },
  {
    id: 2,
    name: "Mutton Biryani",
    category: "Biryani",
    price: 349,
    emoji: "🍖",
    description: "Tender mutton pieces layered with fragrant basmati rice.",
    imageUrl: `https://images.unsplash.com/photo-1589302168068-964664d93dc0${imageParams}`,
  },
  {
    id: 3,
    name: "Egg Biryani",
    category: "Biryani",
    price: 179,
    emoji: "🥚",
    description: "Boiled eggs, biryani rice and spicy salan.",
    imageUrl: `https://images.unsplash.com/photo-1596797038530-2c107229654b${imageParams}`,
  },
  {
    id: 4,
    name: "Chicken 65",
    category: "Starters",
    price: 189,
    emoji: "🔥",
    description: "Crispy fried chicken tossed with curry leaves and chilli.",
    imageUrl: `https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec${imageParams}`,
  },
  {
    id: 5,
    name: "Tandoori Chicken",
    category: "Starters",
    price: 299,
    emoji: "🍗",
    description: "Charred, smoky chicken with classic tandoori spices.",
    imageUrl: `https://images.unsplash.com/photo-1598515214211-89d3c73ae83b${imageParams}`,
  },
  {
    id: 6,
    name: "Chicken Lollipop",
    category: "Starters",
    price: 219,
    emoji: "🍢",
    description: "Crunchy chicken wings served with hot garlic dip.",
    imageUrl: `https://images.unsplash.com/photo-1527477396000-e27163b481c2${imageParams}`,
  },
  {
    id: 7,
    name: "Fish Fry",
    category: "Seafood",
    price: 239,
    emoji: "🐟",
    description: "Masala-marinated fish shallow fried till crisp.",
    imageUrl: `https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2${imageParams}`,
  },
  {
    id: 8,
    name: "Prawn Masala",
    category: "Seafood",
    price: 329,
    emoji: "🦐",
    description: "Prawns cooked in spicy onion tomato gravy.",
    imageUrl: `https://images.unsplash.com/photo-1565680018434-b513d5e5fd47${imageParams}`,
  },
  {
    id: 9,
    name: "Butter Chicken",
    category: "Curries",
    price: 279,
    emoji: "🍛",
    description: "Creamy tomato gravy with soft chicken tikka pieces.",
    imageUrl: `https://images.unsplash.com/photo-1603894584373-5ac82b2ae398${imageParams}`,
  },
  {
    id: 10,
    name: "Chicken Curry",
    category: "Curries",
    price: 229,
    emoji: "🥘",
    description: "Homestyle chicken curry with rich masala.",
    imageUrl: `https://images.unsplash.com/photo-1604908176997-125f25cc6f3d${imageParams}`,
  },
  {
    id: 11,
    name: "Mutton Rogan Josh",
    category: "Curries",
    price: 379,
    emoji: "🍖",
    description: "Slow-cooked mutton in deep red Kashmiri gravy.",
    imageUrl: `https://images.unsplash.com/photo-1631452180519-c014fe946bc7${imageParams}`,
  },
  {
    id: 12,
    name: "Egg Curry",
    category: "Curries",
    price: 149,
    emoji: "🥚",
    description: "Boiled eggs in a flavorful spicy curry.",
    imageUrl: `https://images.unsplash.com/photo-1582169296194-e4d644c48063${imageParams}`,
  },
  {
    id: 13,
    name: "Chicken Tikka Roll",
    category: "Rolls",
    price: 169,
    emoji: "🌯",
    description: "Soft paratha wrapped with chicken tikka and salad.",
    imageUrl: `https://images.unsplash.com/photo-1626700051175-6818013e1d4f${imageParams}`,
  },
  {
    id: 14,
    name: "Mutton Seekh Roll",
    category: "Rolls",
    price: 219,
    emoji: "🌯",
    description: "Juicy seekh kebab roll with mint mayo.",
    imageUrl: `https://images.unsplash.com/photo-1565299585323-38d6b0865b47${imageParams}`,
  },
  {
    id: 15,
    name: "Chicken Fried Rice",
    category: "Chinese",
    price: 179,
    emoji: "🍚",
    description: "Wok-tossed rice with chicken, egg and vegetables.",
    imageUrl: `https://images.unsplash.com/photo-1603133872878-684f208fb84b${imageParams}`,
  },
  {
    id: 16,
    name: "Chicken Noodles",
    category: "Chinese",
    price: 179,
    emoji: "🍜",
    description: "Street-style noodles tossed with chicken strips.",
    imageUrl: `https://images.unsplash.com/photo-1569718212165-3a8278d5f624${imageParams}`,
  },
  {
    id: 17,
    name: "Chilli Chicken",
    category: "Chinese",
    price: 229,
    emoji: "🌶️",
    description: "Indo-Chinese chicken with peppers and spicy sauce.",
    imageUrl: `https://images.unsplash.com/photo-1601050690597-df0568f70950${imageParams}`,
  },
  {
    id: 18,
    name: "Pepper Chicken",
    category: "Starters",
    price: 239,
    emoji: "🧂",
    description: "South-style chicken coated in black pepper masala.",
    imageUrl: `https://images.unsplash.com/photo-1598514982901-ae62764ae75e${imageParams}`,
  },
];
